### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by preterive** [cydolo/AntiBadges#1]
Hello,
not working in modern systems with PHP 7. the script is very Bad because it installs Apache. I have nginx. I can't usw it with the PHP commanf too, becausd i habe php7 (ubuntu 16.04 minimal).

**Comment by cydolo** [comment]
I'm using `Debian 9.8` with `PHP 7.0.19-1` and it works fine.
I have changed something try it again.
If an error occurs please send a screenshot
